{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "agentic-hive.fullname" . }}
  labels:
    {{- include "agentic-hive.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "agentic-hive.selectorLabels" . | nindent 8 }}
{{- end }}
